theme: jekyll-theme-minimal
title: Iyad El Khoury's homepage
description: Welcome to my website, I am currently a student at l'École Polytechnique passionate for mathematics, computer science and the many links between them.

